image: maven:3.5.4-jdk-8

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
  - .m2/repository
  - target/

build:
  stage: build
  tags:
    - userJava8
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  tags:
    - userJava8
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  tags:
    - userJava8
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master

#stages:
#  - install_plugins
#  - package
#  - install
#  - deploy
#
#.validate: &validate
#  stage: build
#  script:
#  - 'mvn $MAVEN_CLI_OPTS test-compile'
#
#.verify: &verify
#  stage: test
#  script:
#  - 'mvn $MAVEN_CLI_OPTS verify site site:stage'
#  except:
#  - master
#
#validate:jdk7:
#  <<: *validate
#  image: maven:3.3.9-jdk-7
#
#validate:jdk8:
#  <<: *validate
#  image: maven:3.3.9-jdk-8
#
#verify:jdk7:
#  <<: *verify
#  image: maven:3.3.9-jdk-7
#
#verify:jdk8:
#  <<: *verify
#  image: maven:3.3.9-jdk-8
#
#
#deploy:jdk8:
#  stage: test
#  script:
#  - 'mvn $MAVEN_CLI_OPTS deploy site site:stage'
#  only:
#  - master
#  artifacts:
#    paths:
#    - target/staging
#  image: maven:3.3.9-jdk-8
#
#
#pages:
#  image: busybox:latest
#  stage: deploy
#  script:
#  - mv target/staging public
#  dependencies:
#  - deploy:jdk8
#  artifacts:
#    paths:
#    - public
#  only:
#  - master