#image: maven:3.5.4-jdk-8
#
#variables:
#  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
#  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
#
#cache:
#  paths:
#  - .m2/repository
#  - target/
#
#build:
#  stage: build
#  tags:
#    - devops-demo
#  script:
#    - mvn $MAVEN_CLI_OPTS compile
#
#test:
#  stage: test
#  tags:
#    - devops-demo
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
#deploy:
#  stage: deploy
#  tags:
#    - devops-demo
#  script:
#    - mvn $MAVEN_CLI_OPTS package
#    - mvn $MAVEN_CLI_OPTS exec:java
#    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.cmcm.DevopsDemoApplication"
#  only:
#    - master
#
#stages:
#  - install_plugins
#  - package
#  - install
#  - deploy
#
#.validate: &validate
#  stage: build
#  script:
#  - 'mvn $MAVEN_CLI_OPTS test-compile'
#
#.verify: &verify
#  stage: test
#  script:
#  - 'mvn $MAVEN_CLI_OPTS verify site site:stage'
#  except:
#  - master
#
#validate:jdk7:
#  <<: *validate
#  image: maven:3.3.9-jdk-7
#
#validate:jdk8:
#  <<: *validate
#  image: maven:3.3.9-jdk-8
#
#verify:jdk7:
#  <<: *verify
#  image: maven:3.3.9-jdk-7
#
#verify:jdk8:
#  <<: *verify
#  image: maven:3.3.9-jdk-8
#
#
#deploy:jdk8:
#  stage: test
#  script:
#  - 'mvn $MAVEN_CLI_OPTS deploy site site:stage'
#  only:
#  - master
#  artifacts:
#    paths:
#    - target/staging
#  image: maven:3.3.9-jdk-8
#
#
#pages:
#  image: busybox:latest
#  stage: deploy
#  script:
#  - mv target/staging public
#  dependencies:
#  - deploy:jdk8
#  artifacts:
#    paths:
#    - public
#  only:
#  - master

stages:
- build
- test
- deploy

build_job:
  stage: build
  script:
  - echo "build starting..."
  tags:
  - devops-demo
  allow_failure: true

clean_build_job:
  stage: build
  script:
  - echo "clean build starting..."
  when: on_failure

test_job:
  stage: test
  script:
  - echo "test starting..."
  tags:
  - devops-demo
  allow_failure: true

dev_deploy_job:
  stage: deploy
  script:
  - echo "dev deploy starting..."
  except:
  - master
  tags:
  - devops-demo
  environment:
    name: dev
    url: http://www.cmcm.com

prod_deploy_job:
  stage: deploy
  script:
  - echo "prod deploy starting..."
  only:
  - master
  tags:
  - devops-demo
  when: manual